export const PATHS = {
    TRACKING: "/tracking",
    REAL_TIME: "/realtime",
    HISTORY: "/history",
    MANAGE: "/manage",
    BUSINESS_REPORT: "/report",
    QCVN_REPORT: "/qcvnreport",
    SUPPORT: "/support",
    DASHBOARD: "/dashboard",
    REPORT: "/report",
    MANAGE_PAGE: {
        STATUS: "/manager/status",
        DEVICES: {
            ADD: "/manager/devices/add",
            LIST: "/manager/devices",
        },
        ACCOUNTS: {
            ADD: "/manager/accounts/add",
            LIST: "/manager/accounts",
        },
    },
};

export const curentDateTimeFormat = "yyyy-MM-DDTHH:mm";
export const curentDateFormat = "yyyy-MM-DD";

export const inputDateFormat = "DD/MM/yyyy";

export const STORES = Object.freeze({
    USER_MANAGER: "USER_MANAGER",
    AGENCY_MANAGER: "AGENCY_MANAGER",
    DEVICE_MANAGER: "DEVICE_MANAGER",
    MODEL_MANAGER: "MODEL_MANAGER",
    NORM_MANAGER: "NORM_MANAGER",
    FUEL_PARAMETER: "FUEL_PARAMETER",
    FUEL_MANAGER: "FUEL_MANAGER",
    RATIO_MANAGER: "RATIO_MANAGER",
    AREA_MANAGER: "AREA_MANAGER",
    TRANSFER_MANAGER: "TRANSFER_MANAGER",
    MANAGER: "MANAGER",
    IMPORT_PRODUCTS: "IMPORT_PRODUCTS",
    MAINTAIN_MANAGER: "MAINTAIN_MANAGER",
    DEVICES_TRANSPORTING: {
        DEVICES_NEED_TO_APPROVE: "DEVICES_TRANSPORTING_DEVICES_NEED_TO_APPROVE",
        DEVICES_SAVED_IN_DB: "DEVICES_TRANSPORTING_DEVICES_SAVED_IN_DB",
    },
    AGENCY_CONFIGURATION: "AGENCY_CONFIGURATION",
    AGENCY_CHARGE: "AGENCY_CHARGE",
    COOPERATIVE_MANAGER: "COOPERATIVE_MANAGER",
    DRIVER_MANAGER: "DRIVER_MANAGER",
    EXPIRATION: "EXPIRATION",
    ROLE_MANAGER: "ROLE_MANAGER",
    PIN_MANAGER: "PIN_MANAGER",
    SYSTEM_MANAGER: "SYSTEM_MANAGER",
    EXTENDING_APPROVAL_MANAGER: "EXTENDING_APPROVAL_MANAGER",
    EXTENDING_SUM_MANAGER: "EXTENDING_SUM_MANAGER",
    AGENCY_EXTENDING_REPORT_MANAGER: "AGENCY_EXTENDING_REPORT_MANAGER",
    NOTICE_MANAGE: "NOTICE_MANAGE",
    SUMMMARY_REPORT: "SUMMMARY_REPORT",
    REALTIME: "REALTIME",
    HISTORY: "HISTORY",
    DASHBOARD: "DASHBOARD",
    EXTEND_SERVICE: "EXTEND_SERVICE",
    COMMUNICATION: "COMMUNICATION",
    WALLET: "WALLET",
    COINTRANSFERLOG: "COINTRANSFERLOG",
    PRODUCT_NOTES: "PRODUCT_NOTES",
    USER_ACTIVITY_LOGS: "USER_ACTIVITY_LOGS",
    EXPORT_PRODUCT_INFOR: "EXPORT_PRODUCT_INFOR",
});

export const ERROR_CODES = {
    UNAUTHORIZED: 401,
    METHOD_NOT_ALLOWED: 405,
};

export const DATE_PICKER_DISPLAY_FORMAT = "DD/MM/YYYY";
export const RSUITE_DATE_PICKER_DISPLAY_FORMAT = "dd/MM/yyyy";
export const DATE_TIME_PICKER_DISPLAY_FORMAT = "DD/MM/YYYY HH:mm:ss";
export const RSUITE_DATE_TIME_PICKER_DISPLAY_FORMAT = "dd/MM/yyyy HH:mm:ss";
export const HISTORY_ITEM_DATE_TIME_DISPLAY_FORMAT = "DD/MM HH:mm:ss";
export const DATAGRID_DATE_FORMAT = "DD/MM/YYYY";
export const DATE_PICKER_URI_FORMAT = "yyyy-MM-DD";
export const SERVER_RESPOND_DATE_TIME_FORMAT = "yyyy-MM-DDTHH:mm:ss";
export const SERVER_RESPOND_DATE_TIME_FORMAT2 = "HH:mm:ss DD-MM-YYYY";
export const SERVER_POSTING_DATE_TIME_FORMAT = "yyyy-MM-DD HH:mm:ss";
export const TIME_ZONE = 7;

export const MINIMUM_SPEED = 3.0;
export const TAB_SYMBOL = "	";
